export const UI_CONSTANTS = {
  // Map Scene
  ENERGY_CRITICAL_THRESHOLD: 0.10,
  SPREAD_PIXELS: 48,
  MOVE_ANIM_MS: 600,
  SLOW_INIT_WARNING_MS: 5000,
  ZOOM_MIN: 0.45,
  ZOOM_MAX: 2.5,
  LAYOUT_RADIUS_X: 330,
  LAYOUT_RADIUS_Y: 220,

  // Main UI
  EVENTS_PANEL_LIMIT: 24,
  REPLAY_STEP_MS: 520,
  CHRONICLE_STORIES_LIMIT: 12,
  STORY_PREVIEW_CHARS: 180,
  BELIEF_FALLBACK_CONFIDENCE: 0.8,
  MEMORIES_PANEL_LIMIT: 4,
  MEMORIES_FULL_LIMIT: 50,
  BELIEFS_PANEL_LIMIT: 3,
};
