"""Generative Arrival Factory — ADR-0011.

Generates unique ArrivalProfile instances via Ollama inference.
Every inhabitant's identity (values, temperament, goals, skills, arrival
memory) originates from generative cognition, never from static defaults.
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass
from typing import Any
from urllib.error import URLError
from urllib.request import Request, urlopen
from uuid import uuid4

from .arrivals import ArrivalProfile
from .models import AgentMind


@dataclass(frozen=True, slots=True)
class ArrivalProvenance:
    provider: str
    model: str
    inference_id: str
    attempts: int
    prompt_version: str = "arrival-genesis-v1"


class ArrivalGenerationUnavailable(RuntimeError):
    def __init__(self, failures: list[dict[str, str]]) -> None:
        super().__init__(
            "no generative provider returned a valid arrival profile"
        )
        self.failures = failures


class GenerativeArrivalFactory:
    """Invokes Ollama to produce a complete ArrivalProfile from minimal seed data.

    The operator provides only a name and optionally a native language.
    Every other identity attribute — values, temperament, goals, skills, and
    the sacred arrival memory — is generated by the model, ensuring each
    Newlander is a unique individual (ADR-0011 [GEN-001]).
    """

    def __init__(
        self,
        model: str = "qwen3:8b",
        endpoint: str = "http://127.0.0.1:11434/api/chat",
        timeout_seconds: float = 120.0,
        max_attempts: int = 3,
    ) -> None:
        self.model = model
        self.endpoint = endpoint
        self.timeout_seconds = timeout_seconds
        self.max_attempts = max_attempts

    def generate(
        self,
        name: str,
        native_language: str = "it",
        location: str = "cittadina_iniziale",
    ) -> tuple[ArrivalProfile, ArrivalProvenance]:
        """Generate a complete ArrivalProfile via Ollama inference.

        Returns the profile and its provenance metadata for auditability.
        Raises ArrivalGenerationUnavailable if all attempts fail.
        """
        agent_id = f"nwl-{int(time.time() * 1000) % 1000000:06d}"
        inference_id = str(uuid4())

        messages = [
            {"role": "system", "content": self._system_prompt()},
            {
                "role": "user",
                "content": json.dumps(
                    {
                        "name": name,
                        "native_language": native_language,
                    },
                    ensure_ascii=False,
                ),
            },
        ]

        failures: list[dict[str, str]] = []
        for attempt in range(1, self.max_attempts + 1):
            try:
                content = self._request(messages)
                parsed = json.loads(content)
                profile = self._parse_profile(
                    parsed, agent_id, name, native_language, location
                )
                provenance = ArrivalProvenance(
                    provider="ollama",
                    model=self.model,
                    inference_id=inference_id,
                    attempts=attempt,
                )
                return profile, provenance
            except (
                RuntimeError,
                TypeError,
                ValueError,
                KeyError,
                json.JSONDecodeError,
            ) as error:
                failures.append({"model": self.model, "error": str(error)})
                messages.extend(
                    [
                        {"role": "assistant", "content": locals().get("content", "")},
                        {
                            "role": "user",
                            "content": (
                                "La risposta precedente non rispettava lo schema: "
                                f"{error}. Rigenera il profilo completo in JSON valido."
                            ),
                        },
                    ]
                )

        raise ArrivalGenerationUnavailable(failures)

    @staticmethod
    def _parse_profile(
        data: dict[str, Any],
        agent_id: str,
        name: str,
        native_language: str,
        location: str,
    ) -> ArrivalProfile:
        """Validate and construct an ArrivalProfile from parsed LLM output."""
        values = data["values"]
        if not isinstance(values, list) or len(values) < 2:
            raise ValueError("values must be a list with at least 2 elements")
        for value in values:
            if not isinstance(value, str) or not value.strip():
                raise ValueError("each value must be a non-empty string")

        temperament = data["temperament"]
        if not isinstance(temperament, list) or len(temperament) < 2:
            raise ValueError("temperament must be a list with at least 2 traits")
        for trait in temperament:
            if not isinstance(trait, str) or not trait.strip():
                raise ValueError("each temperament trait must be a non-empty string")

        goals = data["goals"]
        if not isinstance(goals, list) or len(goals) < 1:
            raise ValueError("goals must be a list with at least 1 element")
        for goal in goals:
            if not isinstance(goal, str) or not goal.strip():
                raise ValueError("each goal must be a non-empty string")

        skills_raw = data.get("skills", {})
        if not isinstance(skills_raw, dict):
            raise ValueError("skills must be a dictionary")
        skills: dict[str, float] = {}
        for key, val in skills_raw.items():
            if not isinstance(key, str) or not key.strip():
                raise ValueError("skill key must be a non-empty string")
            fval = float(val)
            if not 0.0 <= fval <= 1.0:
                raise ValueError(f"skill {key} proficiency must be between 0 and 1")
            skills[key] = fval

        arrival_memory = data["arrival_memory"]
        if not isinstance(arrival_memory, str) or len(arrival_memory.strip()) < 20:
            raise ValueError(
                "arrival_memory must be a vivid first-person recollection "
                "(at least 20 characters)"
            )

        mind = AgentMind(
            agent_id=agent_id,
            name=name,
            values=[v.strip() for v in values],
            temperament=[t.strip() for t in temperament],
            goals=[g.strip() for g in goals],
        )

        return ArrivalProfile(
            mind=mind,
            native_language=native_language,
            arrival_memory=arrival_memory.strip(),
            language_proficiencies={native_language: 1.0},
            skills=skills,
            location=location,
        )

    def _request(self, messages: list[dict[str, str]]) -> str:
        payload = {
            "model": self.model,
            "stream": False,
            "think": False,
            "format": self._schema(),
            "options": {
                "temperature": 0.9,
                "num_ctx": 8192,
                "num_predict": 1024,
            },
            "messages": messages,
        }
        request = Request(
            self.endpoint,
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urlopen(request, timeout=self.timeout_seconds) as response:
                body = json.loads(response.read().decode("utf-8"))
        except (OSError, URLError, TimeoutError, json.JSONDecodeError) as error:
            raise RuntimeError(f"Ollama inference failed: {error}") from error
        try:
            return str(body["message"]["content"])
        except (KeyError, TypeError) as error:
            raise RuntimeError(
                f"Ollama returned no content: {error}"
            ) from error

    @staticmethod
    def _system_prompt() -> str:
        return (
            "Sei il generatore di identità per i nuovi abitanti di Newland, "
            "un universo parallelo terrestre disaccoppiato dal mondo reale.\n\n"
            "REGOLE DELL'UNIVERSO:\n"
            "- Amnesia Primordiale: gli abitanti non ricordano nulla del vecchio mondo "
            "(denaro, proprietà, cellulari, social network, consumismo). "
            "L'unica memoria preservata è il ricordo della transizione.\n"
            "- La Transizione Invisibile: il passaggio dal mondo reale a Newland avviene "
            "in modo quotidiano e graduale — una deviazione stradale, una svolta sbagliata, "
            "un sentiero che cambia impercettibilmente. Non ci sono portali fantascientifici.\n"
            "- Il Loop del Ritorno: tentando di tornare indietro, la geometria circolare "
            "riporta sempre al Punto di Arrivo.\n"
            "- La Cittadina Iniziale: il primo luogo conosciuto è una cittadina primordiale "
            "con vegetazione e clima terrestri, ma impregnata di un'atmosfera sottile e strana.\n\n"
            "COMPITO:\n"
            "Dato il nome e la lingua madre di un nuovo abitante, genera la sua identità unica:\n"
            "- values: 2-4 valori profondi che guidano questa persona (in italiano)\n"
            "- temperament: 2-4 tratti di temperamento distintivi (in italiano)\n"
            "- goals: 1-2 obiettivi iniziali personali al momento dell'arrivo (in italiano)\n"
            "- skills: 2-3 competenze pratiche con proficiency 0.0-1.0 (chiavi in italiano)\n"
            "- arrival_memory: il ricordo vivido, personale e in prima persona della "
            "transizione verso Newland. Deve essere unico, sensoriale, specifico. "
            "Descrivi come questa persona specifica ha attraversato la soglia — "
            "stava guidando? camminando? in bicicletta? Cosa ha notato cambiare "
            "nell'ambiente? Che sensazione fisica ha provato? (in italiano, 2-4 frasi)\n\n"
            "L'identità deve riflettere il nome e la cultura d'origine della persona. "
            "Non usare cliché. Ogni persona è radicalmente diversa.\n"
            "Restituisci soltanto il JSON richiesto."
        )

    @staticmethod
    def _schema() -> dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "values": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 2,
                    "maxItems": 4,
                },
                "temperament": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 2,
                    "maxItems": 4,
                },
                "goals": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 1,
                    "maxItems": 2,
                },
                "skills": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "minimum": 0,
                        "maximum": 1,
                    },
                },
                "arrival_memory": {
                    "type": "string",
                    "minLength": 20,
                },
            },
            "required": [
                "values",
                "temperament",
                "goals",
                "skills",
                "arrival_memory",
            ],
            "additionalProperties": False,
        }
